- name: Provision a GeoNode into Production
  hosts: production
  remote_user: ubuntu
  vars:
    app_name: eventkit_geonode
    github_user: disruptivegeo 
    server_name: data.sandhillgeo.com
    deploy_user: ubuntu
    code_repository: https://github.com/disruptivegeo/eventkit_geonode.git"
    branch_name: master
    virtualenv_dir: "/home/ubuntu/.venvs"
    site_url: "http://data.sandhillgeo.com/geoserver/"
    geoserver_url: "http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war"
  roles:
     - { role: GeoNode.geonode }
